spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    show-sql: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/battleship
    username: postgres
    password: admin

