spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/battleship
    username: postgres
    password: admin
battleship:
  clear-timeout: 0 */1 * ? * *

